* English with a Panda 🏴󠁧󠁢󠁥󠁮󠁧󠁿

One of the best sources for gathering the description for words is [[https://dictionary.cambridge.org/][Cambridge Dictionary]].

** Definitions
- absent-minded (adj) :: forgetful
- acquainted (adj) :: with sth (formal) familiar with sth, having read, seen or experienced it
- adept (adj) :: very good at doing something that is not easy
- adjutant (n) :: adjutant is a military appointment given to an officer who assists the commanding officer with unit administration, mostly the management of human resources in an army unit
- affection (n) :: the feeling of liking or loving sb/sth very much and caring about them
- aisle (n) :: a long, narrow space between rows of seats in an aircraft, cinema, or church
- amalgamation (n) :: the process in which separate organizations unite to form a larger organization or group, or an organization or group formed in this way
- anthem (n) :: a song that has special importance for a particular group of people, an organization, or a country, often sung on a special occasion
- antidote (n) :: a chemical, especially a drug, that limits the effects of a poison
- asylum (n) :: a mental hospital, or any other institution giving shelter and other help to poor or suffering people
- asylum (n) :: protection that a government gives to people who have left their own country, usually because they were in danger for political reason
- asylum seeker :: An asylum seeker is a person who leaves their country of residence, enters another country and applies for asylum in that other country
- audition (n) :: a short performance given by an actor, a singer, etc, so that sb can decide whether they are suitable to act in a play, sing in a concert, etc
- avalanche (n) :: a mass of snow, ice and rock that falls down the side of a mountain
- bargain (n) :: something on sale at a lower price than its true value
- bay (n) :: a part of the coast where the land curves in so that the sea is surrounded by land on three sides
- besotted (adj) :: loving sb/sth so much that you do not behave in a sensible way
- bespoke (adj) ::  made specially, according to the needs of an individual customer
- booty (n) :: valuable things that are stolen, especially by soldiers in a time of war
- boycott (v) :: withdraw from commercial or social relations with (a country, organization, or person) as a punishment or protest.
- bribe (n)(v) :: a sum of money or sth valuable that you give or offer to sb to persuade them to help you, especially by doing sth dishonest
- bun (n) :: a small, round piece of bread, especially one that is cut horizontally and holds a burger
- bust (v) :: if the police bust someone, they charge him/her with a crime
- bust (v) :: to break something
- cape (n) :: a very large piece of land sticking out into the sea
- cavalry (n) :: the part of the army that fought on horses; the part of the modern army that uses armed vehicles
- clutter (n)(v) :: to fill a place with too many things, so that it is untidy
- commute (v)(n) :: to travel regularly by bus, train, car, etc. between your place of work and your home
- compromise (n)(v) :: an agreement made between two people or groups in which each side gives up some of the things they want so that both sides are happy at the end
- confluence (n) :: a situation in which two things come together or happen at the same time
- conscript (n) :: a person who has been forced to serve in an army or in one of a country's armed forces
- coroner (n) :: an official whose job is to discover the cause of any sudden, violent or suspicious death by holding an inquest
- covert (adj)(n) :: secret or hidden, making it difficult to notice
- crate (n) :: a large wooden container for transporting goods
- crate (v) :: to put something into a crate, especially in order to move it
- curfew (n) :: a law which says that people must not go outside after a particular time at night until the morning; the time after which nobody must go outside
- dangerous (adj) :: hazardous; perilous; risky
- deaden (v) :: to make sth such as a sound, a feeling, etc. less strong
- decent (adj) :: of a good enough standard or quality
- decoy (n) :: an animal or a bird, or a model of one, that attracts other animals or birds, especially so that they can be shot by people who are hunting them
- dignity (n) :: the fact of being given honor and respect by people
- disguise (n) :: to change your appearance so that people cannot recognize you
- dressed (adj) :: wearing clothes and not naked or wearing clothes for sleeping
- drill (n)(v) :: a way of learning sth by means of repeated exercises
- economies of scale (n) :: the reduction of production costs that is a result of making and scaling goods in large quantities
- emigrant (n) :: a person who leaves their country to live in another
- entail (v) :: to have (something) as a part, step, or result
- excuse (or pardon) my French :: used to apologize for swearing. informal
- facade (n) :: the front of a building
- falter (v) :: to become weaker or less effective
- fatigue (n) :: a feeling of being extremely tired, usually because of hard work or exercise
- fold (v)(n) :: to bend sth so that it becomes smaller or flatter and can be stored or carried more easily
- fond (adj) :: to like someone or something very much
- foosball (n) :: Table football, also known as foosball[a] or table soccer, is a tabletop game loosely based on association football.
- guerrilla (n) :: a member of a small group of soldiers who are not part of an official army and who fight against official soldiers, usually to try to change the government
- hazelnut (n) :: the small brown nut of the hazel tree
- hell (n) :: an extremely unpleasant or difficult place, situation, or experience
- herb (n) :: a plant whose leaves, flowers or seeds are used to flavor food, in medicines or for their pleasant smell.
- heyday (n) :: the time when sb/sth had most power or success, or was most popular
- imitation (n) :: made to look like something else:
- immigrant (n) :: a person who has come to live permanently in a country that is not their own
- impulsive (adj) :: impatient
- inclined (adj) :: tending to do sth; likely to do sth
- inhibitor (n) :: a substance which delays or prevents a chemical reaction
- insatiable (adj) :: always wanting more of sth; not able to be satisfied
- instrumentation (n) :: a set of instruments used in operating a vehicle or a piece of machinery
- intimidating (adj) :: frightening in a way which makes a person feel less confident
- javelin (b) :: a light spear thrown as a weapon of war or in hunting
- lenient (adj) :: not harsh, severe, or strict
- locket (n) :: a small piece of jewellery that opens to show a small picture or piece of hair, usually worn on a chain around a person's neck
- mediocre (adj) :: not very good; of only average standard
- mediocrity (n) :: moderate ability or value
- molest (v) :: to make unwanted or improper sexual advances towards (someone)
- monk (n) :: a member of a religious group of men who often live apart from other people in a monastery and who do not marry or have personal possessions.
- mote (n) :: a very small piece of dust
- motif (n) :: a design or a pattern used as a decoration
- nomad (n) :: a member of a community that moves with its animals from place to place
- nomadic (adj) :: moving from one place to another rather than living in one place all of the time.
- nuance (n) :: a very slight difference in meaning, sound, color or sb's feelings that is not usually very obvious
- obese (adj) :: extremely fat in a way that is dangerous for health
- obscure (adj)(v) :: not well known
- overtaking (n) :: the act of coming from behind another vehicle or person and moving in front of it or them
- pad (n) :: the place where sb lives, especially a flat/apartment
- parcel (n) :: an area of land
- parcel (n) :: an object or collection of objects wrapped in paper, especially so that it can be sent by post
- pension (n) :: an amount of money paid regularly by a government or company to sb who is considered to be too old or too ill/sick to work
- perpendicular (adj)(n) :: (technical) forming an angle of 90° with another line or surface
- perseverance (n) :: the quality of continuing to try to achieve a particular aim despite difficulties
- pesticide (n) :: a substance used for destroying insects or other organisms harmful to cultivated plants or to animals.
- pestilence (n) :: any infectious disease that spreads quickly and kills a lot of people
- petition (n)(v) :: (against/for sth) a written document signed by a large number of people that asks sb in a position of authority to do or change sth
- pilgrim (n) :: one who travels to a shrine or holy place as a devotee
- pitch (n)(v) :: an area of ground specially prepared and marked for playing a sports game
- plumbing (n) :: the system of pipes, etc. that supply water to a building
- polyglot (adj) :: knowing, using or written in more than one language
- posse (n) :: A posse is a group of friends, or a group of people who are gathered together for a particular purpose.
- prevail (v) :: (in/among sth) to exist or be very common at a particular time or in a particular place
- prevalent (adj) :: that exists or is very common at a particular time or in a particular place
- proactive (adj) :: controlling a situation by making things happen rather than waiting for things to happen and then reacting to them
- proceeding (n) :: (plural) the official written report of a meeting, etc
- profile (n) :: the outline of a person's face when you look from the side, not the front
- reactive (adj) :: showing a reaction or response
- reign (n)(v) :: the period during which sb is in charge of an organization, a team, etc
- reluctant (adj) :: hesitating before doing sth because you do not want to do it or because you are not sure that it is the right thing to do
- remark (n) :: something that you say, giving your opinion about something or stating a fact
- ritual (n)  :: a series of actions that are always performed in the same way, especially as part of a religious ceremony
- rival (n)(adj)(v) :: a person, company, or thing that competes with another in sport, business, etc
- scribe (n) :: a person who made copies of written documents before printing was invented
- sewer (n) :: an underground pipe that is used to carry sewage away from houses, factories, etc
- shaft (n)(v) :: a long, narrow, usually vertical passage in a building or underground, used especially for a lift/elevator or as a way of allowing air in or out
- sorrow (n)(v) :: (rather formal) a feeling of great sadness because sth very bad has happened
- spore (n) :: one of the very small cells that are produced by some plants and that develop into new plants
- STEM (n) :: science, technology, engineering, and math
- stereotype (n)(v) :: a fixed idea or image that many people have of a particular type of person or thing, but which is often not true in reality
- stink (v)(n) :: (of sth) to have a strong, unpleasant smell
- stopgap (n) :: something that you use or do for a short time while you are looking for sth better
- stumble (v) :: to walk or move in an unsteady way
- stunt (n)(v) :: a dangerous and difficult action that sb does to entertain people, especially as part of a film/movie
- suit (n) :: a set of clothes or a piece of clothing to be worn in a particular situation or while doing a particular activity
- susceptible (adj) :: very likely to be influenced, harmed or affected by sb/sth
- tap (v)(n) :: to fit a device to a telephone so that sb's calls can be listened to secretly
- the shopping period (n) :: the period in which students can decide on their courses before starting the semester
- tide (n) :: the alternate rising and falling of the surface of the ocean
- tombstone (n) :: gravestone
- triage (n) :: the process of quickly examining patients who are taken to a hospital in order to decide which ones are the most seriously ill and must be treated first
- triumph (n) :: the feeling of great satisfaction or joy that you get from a great success or victory
- tuxedo (n) :: a man's black or white jacket worn at formal social events, usually in the evening, with matching trousers and a bow tie
- tyrannical (adj) :: using power or authority over people in an unfair and cruel way
- unfettered (adj) :: not limited by rules or any other
- utmost (adj) :: used to emphasize how important or serious something is
- vague (adj) :: ambiguous, murky; opaque; not clear in a person's mind
- vast (adj) :: extremely large in area, size, amount, etc.
- venerable (adj) :: people or things deserve respect because they are old, important, wise, etc
- venom (n) :: a poisonous liquid that some snakes, insects, etc. produce and can put into another animal's body by biting or stinging
- vent (n) :: an opening that allows air, gas or liquid to pass out of or into a room, building, container, etc
- vivid (adj) :: (of memories, a description, etc.) producing very clear pictures in your mind
- wasting (adj) :: a wasting disease or illness is one that causes sb to gradually become weaker and thinner



** By Example
- He expressed his sorrow at the news of her death.
- the joys and sorrows of childhood
- His death was a great sorrow to everyone who knew him.
- He noted, with some irritation, that the letter had not been sent.
- I apologized to my teacher for being late to the class.
- a bee always stings me.
- a bee stung me.
- I've gotten fired. / I got fired.
- What would you do if you were me? (suggestion) If I were you, I would call the police
- I lost my touch with my friend.
- I'm fond of traveling.
- I'm interested in reading fictional novel.
- I'm in my late 20s.
- I'm in my early 30s.
- I'm in my mid 40s.
- 1930s :: a decade; a period of 10 years
*** know
- I've known him for a long time [How long have you known him?]
*** recognize
- Don't you recognize me
*** swole
- If you're swole you'll look good in anything
** Synonyms
- keen on / fund of / into / eager about / interested in
- indecisive / hesitant / doubtful / uncertain
